version: '3.5'

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /var/leklund/data/html
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /var/leklund/data/mysql

# networks:
#   network:
#     name: inception-network


networks:
  inception-network:


services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:leklund
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - inception-network
    volumes:
      - wordpress:/var/www/html

  wordpress:
    container_name: wordpress
    image: wordpress:leklund
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    restart: always
    env_file:
      - .env
    networks:
      - inception-network
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb:leklund
    build: ./requirements/mariadb/.
    restart: always
    env_file:
      - .env
    networks:
      - inception-network
    volumes:
      - mariadb:/var/lib/mysql
